#!/bin/zsh

# this file was generated by situational-template-generator v1.2
# (c)2021 osirisgothra/gabriel t sharp

declare -ga toedit=(
	banana_bread.png
	banana_dough.png
	banana_tree_sapling.png
	banana_trunk.png
	banana_trunk_top.png
	banana_wood.png
	bowl.png
	brick_ice.png
	brick_snow.png
	bucket_cactus.png
	candle.png
	candle_static.png
	charcoal_lump.png
	coral2.png
	coral3.png
	coral4.png
	coral5.png
	crystal_axe.png
	crystal_gilly_staff.png
	crystal_ingot.png
	crystal_pick.png
	crystal_shovel.png
	crystal_spike.png
	crystal_sword.png
	default_apple_gold.png
	default_gate_overlay.png
	ethereal_big_tree_sapling.png
	ethereal_crystalgrass.png
	ethereal_dry_dirt.png
	ethereal_dry_shrub.png
	ethereal_frost_leaves.png
	ethereal_frost_tree.png
	ethereal_frost_tree_sapling.png
	ethereal_frost_tree_top.png
	ethereal_grass_bamboo_side.png
	ethereal_grass_bamboo_top.png
	ethereal_grass_cold_side.png
	ethereal_grass_cold_top.png
	ethereal_grass_crystal_side.png
	ethereal_grass_crystal_top.png
	ethereal_grass_fiery_side.png
	ethereal_grass_fiery_top.png
	ethereal_grass_gray_side.png
	ethereal_grass_gray_top.png
	ethereal_grass_grove_side.png
	ethereal_grass_grove_top.png
	ethereal_grass_jungle_side.png
	ethereal_grass_jungle_top.png
	ethereal_grass_mushroom_side.png
	ethereal_grass_mushroom_top.png
	ethereal_grass_prairie_side.png
	ethereal_grass_prairie_top.png
	ethereal_gray_tree_sapling.png
	ethereal_jungle_tree_sapling.png
	ethereal_mushroom_garden_1.png
	ethereal_mushroom_garden_2.png
	ethereal_mushroom_garden_3.png
	ethereal_mushroom_garden_4.png
	ethereal_mushroom_sapling.png
	ethereal_pine_tree_sapling.png
	ethereal_snowygrass.png
	ethereal_tree_sapling.png
	ethereal_wild_onion_1.png
	ethereal_wild_onion_2.png
	ethereal_wild_onion_3.png
	ethereal_wild_onion_4.png
	ethereal_wild_onion_5.png
	fern.png
	fern_tubers.png
	fish_cooked.png
	fish_raw.png
	fishing_rod.png
	fishing_rod_baited.png
	fishing_rod_wield.png
	frost_wood.png
	glostone.png
	hearty_stew.png
	hearty_stew_cooked.png
	illumishroom.png
	illumishroom2.png
	illumishroom3.png
	moretrees_acacia_leaves.png
	moretrees_acacia_sapling.png
	moretrees_acacia_trunk.png
	moretrees_acacia_trunk_top.png
	moretrees_acacia_wood.png
	moretrees_coconut_slice.png
	mushroom.png
	mushroom_block.png
	mushroom_pore.png
	mushroom_soup.png
	mushroom_soup_cooked.png
	mushroom_spores.png
	mushroom_trunk.png
	mushroom_trunk_top.png
	obsidian_brick.png
	orange_leaves.png
	orange_tree_sapling.png
	paper_wall.png
	pine_leaves.png
	pine_nuts.png
	purple_leaves.png
	red_leaves.png
	redwood_leaves.png
	redwood_sapling.png
	redwood_trunk.png
	redwood_trunk_top.png
	redwood_wood.png
	sashimi.png
	scarlet_leaves.png
	scorched_tree.png
	scorched_tree_top.png
	seaweed.png
	stone_ladder.png
	strawberry_1.png
	strawberry_2.png
	strawberry_3.png
	strawberry_4.png
	strawberry_5.png
	strawberry_6.png
	strawberry_7.png
	strawberry_8.png
	vine.png
	wild_onion.png
	willow_twig.png
	worm.png
	yellow_leaves.png
	yellow_tree.png
	yellow_tree_sapling.png
	yellow_tree_top.png
	yellow_wood.png
)
declare -ga pathedit=( "$PWD/"${^toedit} )
for x in $pathedit; do
    dims=$(file "$x" | grep '[0-9]+ x [0-9]+' -Po)
    printf "%25s %10s\n" ${x: 0:20} $dims    
    [[ $1 == conv ]] && convert "$x" -strip -colorspace RGB -adaptive-resize 64x64 "png32:$x"
   
done


if [[ $1 == doit ]]; then
    qfork gimp $pathedit
else
    echo qfork gimp $pathedit
fi