#!/bin/sh
cp blue_tinted_glass.png cyan_tinted_glass.png
cp blue_tinted_glass.png green_tinted_glass.png
cp blue_tinted_glass.png gray_tinted_glass.png
cp blue_tinted_glass.png magenta_tinted_glass.png
cp blue_tinted_glass.png red_tinted_glass.png
cp blue_tinted_glass.png white_tinted_glass.png
cp blue_tinted_glass.png yellow_tinted_glass.png


